<%@ Page Language="C#" AutoEventWireup="true" CodeFile="String_Format.aspx.cs" Inherits="Ch03_WebControls_String_Format" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">


<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <title>String_Format</title>
</head>
<body>
    <form id="form1" runat="server">
    <div>

        <asp:Button ID="Button1" runat="server" Text="按下按鈕，將會呈現出字串格式"
            OnClick="Button1_Click" />

    </div>
    <br />
    數字(-123與 -123.45F)----<br />
    <asp:Label ID="Label1" runat="server" Style="color: #0000FF"></asp:Label>
    <hr />
    <p>
        日期----
    </p>
    <p>
        &nbsp;<asp:Label ID="Label2" runat="server" Style="color: #339933"></asp:Label>
    </p>
        <p>
            &nbsp;</p>
        <p>
            &nbsp;</p>
        <p>
            &nbsp;</p>
        <div class="toclevel1 current" data-childrenloaded="true" data-toclevel="1" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif; overflow-x: hidden; white-space: normal; width: auto; margin-bottom: 5px; padding-left: 17px; color: rgb(0, 0, 0); font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
            <a id="hh141434_VS.110_zh-tw" data-tochassubtree="true" href="http://msdn.microsoft.com/zh-tw/library/26etazsy(v=vs.110).aspx" mtpsaliasid="" mtpsassetid="0d1364da-5b30-4d42-8e6b-03378343343f_VS.110_zh-tw" mtpsshortid="26etazsy_VS.110_zh-tw" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; text-decoration: none; color: rgb(0, 0, 0); display: block; margin-left: 18px; overflow: hidden; font-weight: bold;" title="格式化類型">格式化類型</a>&nbsp;&nbsp; <a href="http://msdn.microsoft.com/zh-tw/library/26etazsy(v=vs.110).aspx">http://msdn.microsoft.com/zh-tw/library/26etazsy(v=vs.110).aspx</a></div>
        <div class="toclevel2" data-toclevel="2" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif; overflow-x: hidden; white-space: normal; width: auto; margin-bottom: 5px; padding-left: 34px; color: rgb(0, 0, 0); font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
            <span class="toc_empty" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; background-image: none; width: 17px; height: 17px; overflow: hidden; float: left; display: inline-block; margin-left: 18px; vertical-align: top; outline: none; background-position: initial initial; background-repeat: initial initial;"></span><a href="http://msdn.microsoft.com/zh-tw/library/dwhawy9k(v=vs.110).aspx" mtpsaliasid="" mtpsassetid="" mtpsshortid="" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; text-decoration: none; color: rgb(19, 100, 196); display: block; margin-left: 18px; overflow: hidden;" title="標準數值格式字串">標準數值格式字串</a></div>
        <div class="toclevel2" data-toclevel="2" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif; overflow-x: hidden; white-space: normal; width: auto; margin-bottom: 5px; padding-left: 34px; color: rgb(0, 0, 0); font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
            <span class="toc_empty" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; background-image: none; width: 17px; height: 17px; overflow: hidden; float: left; display: inline-block; margin-left: 18px; vertical-align: top; outline: none; background-position: initial initial; background-repeat: initial initial;"></span><a href="http://msdn.microsoft.com/zh-tw/library/0c899ak8(v=vs.110).aspx" mtpsaliasid="" mtpsassetid="" mtpsshortid="" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; text-decoration: none; color: rgb(19, 100, 196); display: block; margin-left: 18px; overflow: hidden;" title="自訂數值格式字串">自訂數值格式字串</a></div>
        <div class="toclevel2" data-toclevel="2" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif; overflow-x: hidden; white-space: normal; width: auto; margin-bottom: 5px; padding-left: 34px; color: rgb(0, 0, 0); font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
            <span class="toc_empty" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; background-image: none; width: 17px; height: 17px; overflow: hidden; float: left; display: inline-block; margin-left: 18px; vertical-align: top; outline: none; background-position: initial initial; background-repeat: initial initial;"></span><a href="http://msdn.microsoft.com/zh-tw/library/az4se3k1(v=vs.110).aspx" mtpsaliasid="" mtpsassetid="" mtpsshortid="" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; text-decoration: none; color: rgb(19, 100, 196); display: block; margin-left: 18px; overflow: hidden;" title="標準日期和時間格式字串">標準日期和時間格式字串</a></div>
        <div class="toclevel2" data-toclevel="2" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif; overflow-x: hidden; white-space: normal; width: auto; margin-bottom: 5px; padding-left: 34px; color: rgb(0, 0, 0); font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
            <span class="toc_empty" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; background-image: none; width: 17px; height: 17px; overflow: hidden; float: left; display: inline-block; margin-left: 18px; vertical-align: top; outline: none; background-position: initial initial; background-repeat: initial initial;"></span><a href="http://msdn.microsoft.com/zh-tw/library/8kb3ddd4(v=vs.110).aspx" mtpsaliasid="" mtpsassetid="" mtpsshortid="" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; text-decoration: none; color: rgb(19, 100, 196); display: block; margin-left: 18px; overflow: hidden;" title="自訂日期和時間格式字串">自訂日期和時間格式字串</a></div>
        <div class="toclevel2" data-toclevel="2" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif; overflow-x: hidden; white-space: normal; width: auto; margin-bottom: 5px; padding-left: 34px; color: rgb(0, 0, 0); font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
            <span class="toc_empty" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; background-image: none; width: 17px; height: 17px; overflow: hidden; float: left; display: inline-block; margin-left: 18px; vertical-align: top; outline: none; background-position: initial initial; background-repeat: initial initial;"></span><a href="http://msdn.microsoft.com/zh-tw/library/ee372286(v=vs.110).aspx" mtpsaliasid="" mtpsassetid="" mtpsshortid="" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; text-decoration: none; color: rgb(19, 100, 196); display: block; margin-left: 18px; overflow: hidden;" title="標準 TimeSpan 格式字串">標準 TimeSpan 格式字串</a></div>
        <div class="toclevel2" data-toclevel="2" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif; overflow-x: hidden; white-space: normal; width: auto; margin-bottom: 5px; padding-left: 34px; color: rgb(0, 0, 0); font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
            <span class="toc_empty" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; background-image: none; width: 17px; height: 17px; overflow: hidden; float: left; display: inline-block; margin-left: 18px; vertical-align: top; outline: none; background-position: initial initial; background-repeat: initial initial;"></span><a href="http://msdn.microsoft.com/zh-tw/library/ee372287(v=vs.110).aspx" mtpsaliasid="" mtpsassetid="" mtpsshortid="" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; text-decoration: none; color: rgb(19, 100, 196); display: block; margin-left: 18px; overflow: hidden;" title="自訂 TimeSpan 格式字串">自訂 TimeSpan 格式字串</a></div>
        <div class="toclevel2" data-toclevel="2" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif; overflow-x: hidden; white-space: normal; width: auto; margin-bottom: 5px; padding-left: 34px; color: rgb(0, 0, 0); font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
            <span class="toc_empty" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; background-image: none; width: 17px; height: 17px; overflow: hidden; float: left; display: inline-block; margin-left: 18px; vertical-align: top; outline: none; background-position: initial initial; background-repeat: initial initial;"></span><a href="http://msdn.microsoft.com/zh-tw/library/c3s1ez6e(v=vs.110).aspx" mtpsaliasid="" mtpsassetid="" mtpsshortid="" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; text-decoration: none; color: rgb(19, 100, 196); display: block; margin-left: 18px; overflow: hidden;" title="列舉類型格式字串">列舉類型格式字串</a></div>
        <div class="toclevel2" data-toclevel="2" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif; overflow-x: hidden; white-space: normal; width: auto; margin-bottom: 5px; padding-left: 34px; color: rgb(0, 0, 0); font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
            <span class="toc_empty" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; background-image: none; width: 17px; height: 17px; overflow: hidden; float: left; display: inline-block; margin-left: 18px; vertical-align: top; outline: none; background-position: initial initial; background-repeat: initial initial;"></span><a href="http://msdn.microsoft.com/zh-tw/library/txafckwd(v=vs.110).aspx" mtpsaliasid="" mtpsassetid="" mtpsshortid="" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; text-decoration: none; color: rgb(19, 100, 196); display: block; margin-left: 18px; overflow: hidden;" title="複合格式">複合格式</a></div>
        <div class="toclevel2" data-childrenloaded="true" data-toclevel="2" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif; overflow-x: hidden; white-space: normal; width: auto; margin-bottom: 5px; padding-left: 34px; color: rgb(0, 0, 0); font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
            <a class="toc_expanded" href="http://msdn.microsoft.com/zh-tw/library/26etazsy(v=vs.110).aspx#" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; background-image: url(http://i3.msdn.microsoft.com/Areas/Epx/Content/Images/ImageSprite.png); background-attachment: scroll; width: 17px; height: 17px; overflow: hidden; text-decoration: none; color: rgb(19, 100, 196); display: inline-block; margin-left: 18px; float: left; vertical-align: top; background-position: -352px -3px; background-repeat: no-repeat no-repeat;"></a>
            <a id="hh768058_VS.110_zh-tw" data-tochassubtree="true" href="http://msdn.microsoft.com/zh-tw/library/bb762912(v=vs.110).aspx" mtpsaliasid="" mtpsassetid="" mtpsshortid="" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; text-decoration: none; color: rgb(19, 100, 196); display: block; margin-left: 18px; overflow: hidden;" title="執行格式化作業">執行格式化作業</a></div>
        <div data-toclevel="3" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif; overflow-x: hidden; white-space: normal; width: auto; margin-bottom: 5px; color: rgb(0, 0, 0); font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; padding-left: 51px;">
            <span class="toc_empty" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; background-image: none; width: 17px; height: 17px; overflow: hidden; float: left; display: inline-block; margin-left: 18px; vertical-align: top; outline: none; background-position: initial initial; background-repeat: initial initial;"></span><a href="http://msdn.microsoft.com/zh-tw/library/dd260048(v=vs.110).aspx" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; text-decoration: none; color: rgb(19, 100, 196); display: block; margin-left: 18px; overflow: hidden;" title="如何：以前置字元零來填補數字">如何：以前置字元零來填補數字</a></div>
        <div data-toclevel="3" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif; overflow-x: hidden; white-space: normal; width: auto; margin-bottom: 5px; color: rgb(0, 0, 0); font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; padding-left: 51px;">
            <span class="toc_empty" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; background-image: none; width: 17px; height: 17px; overflow: hidden; float: left; display: inline-block; margin-left: 18px; vertical-align: top; outline: none; background-position: initial initial; background-repeat: initial initial;"></span><a href="http://msdn.microsoft.com/zh-tw/library/bb762911(v=vs.110).aspx" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; text-decoration: none; color: rgb(19, 100, 196); display: block; margin-left: 18px; overflow: hidden;" title="如何：從特定日期擷取一星期的哪一日">如何：從特定日期擷取一星期的哪一日</a></div>
        <div data-toclevel="3" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif; overflow-x: hidden; white-space: normal; width: auto; margin-bottom: 5px; color: rgb(0, 0, 0); font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; padding-left: 51px;">
            <span class="toc_empty" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; background-image: none; width: 17px; height: 17px; overflow: hidden; float: left; display: inline-block; margin-left: 18px; vertical-align: top; outline: none; background-position: initial initial; background-repeat: initial initial;"></span><a href="http://msdn.microsoft.com/zh-tw/library/bb762932(v=vs.110).aspx" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; text-decoration: none; color: rgb(19, 100, 196); display: block; margin-left: 18px; overflow: hidden;" title="如何：定義和使用自訂數值格式提供者">如何：定義和使用自訂數值格式提供者</a></div>
        <div data-toclevel="3" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif; overflow-x: hidden; white-space: normal; width: auto; margin-bottom: 5px; color: rgb(0, 0, 0); font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; padding-left: 51px;">
            <span class="toc_empty" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; background-image: none; width: 17px; height: 17px; overflow: hidden; float: left; display: inline-block; margin-left: 18px; vertical-align: top; outline: none; background-position: initial initial; background-repeat: initial initial;"></span><a href="http://msdn.microsoft.com/zh-tw/library/bb882584(v=vs.110).aspx" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; text-decoration: none; color: rgb(19, 100, 196); display: block; margin-left: 18px; overflow: hidden;" title="如何：反覆存取日期和時間值">如何：反覆存取日期和時間值</a></div>
        <div data-toclevel="3" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif; overflow-x: hidden; white-space: normal; width: auto; margin-bottom: 5px; color: rgb(0, 0, 0); font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; padding-left: 51px;">
            <span class="toc_empty" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; background-image: none; width: 17px; height: 17px; overflow: hidden; float: left; display: inline-block; margin-left: 18px; vertical-align: top; outline: none; background-position: initial initial; background-repeat: initial initial;"></span><a href="http://msdn.microsoft.com/zh-tw/library/bb762964(v=vs.110).aspx" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; text-decoration: none; color: rgb(19, 100, 196); display: block; margin-left: 18px; overflow: hidden;" title="如何：將使用者輸入 Web 控制項的數值轉換成數字">如何：將使用者輸入 Web 控制項的數值轉換成數字</a></div>
        <div data-toclevel="3" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif; overflow-x: hidden; white-space: normal; width: auto; margin-bottom: 5px; color: rgb(0, 0, 0); font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; padding-left: 51px;">
            <span class="toc_empty" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; background-image: none; width: 17px; height: 17px; overflow: hidden; float: left; display: inline-block; margin-left: 18px; vertical-align: top; outline: none; background-position: initial initial; background-repeat: initial initial;"></span><a href="http://msdn.microsoft.com/zh-tw/library/bb882561(v=vs.110).aspx" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; text-decoration: none; color: rgb(19, 100, 196); display: block; margin-left: 18px; overflow: hidden;" title="如何：對 Web 使用者顯示當地語系化的日期和時間資訊">如何：對 Web 使用者顯示當地語系化的日期和時間資訊</a></div>
        <div data-toclevel="3" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif; overflow-x: hidden; white-space: normal; width: auto; margin-bottom: 5px; color: rgb(0, 0, 0); font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; padding-left: 51px;">
            <span class="toc_empty" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; background-image: none; width: 17px; height: 17px; overflow: hidden; float: left; display: inline-block; margin-left: 18px; vertical-align: top; outline: none; background-position: initial initial; background-repeat: initial initial;"></span><a href="http://msdn.microsoft.com/zh-tw/library/bb882581(v=vs.110).aspx" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; text-decoration: none; color: rgb(19, 100, 196); display: block; margin-left: 18px; overflow: hidden;" title="如何：在日期與時間值中顯示毫秒">如何：在日期與時間值中顯示毫秒</a></div>
        <div data-toclevel="3" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif; overflow-x: hidden; white-space: normal; width: auto; margin-bottom: 5px; color: rgb(0, 0, 0); font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; padding-left: 51px;">
            <span class="toc_empty" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; background-image: none; width: 17px; height: 17px; overflow: hidden; float: left; display: inline-block; margin-left: 18px; vertical-align: top; outline: none; background-position: initial initial; background-repeat: initial initial;"></span><a href="http://msdn.microsoft.com/zh-tw/library/bb882586(v=vs.110).aspx" style="font-family: 'Microsoft JhengHei UI', 'Microsoft JhengHei', PMingLiU, MingLiU, 'Segoe UI', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif !important; text-decoration: none; color: rgb(19, 100, 196); display: block; margin-left: 18px; overflow: hidden;" title="如何：在非西曆中顯示日期">如何：在非西曆中顯示日期</a></div>
        <p>
            &nbsp;</p>
    </form>

</body>
</html>
